### ISSUE TITLE
it  can't work

### ISSUE THREAD

**Issue by zxhycxq** [eetann/choomame#54]
I install it on chrome,but it can't work in google search page. 
![image](https://user-images.githubusercontent.com/11674203/183282332-df6d970c-7737-4920-942c-a7eb0093de54.png)

https://github.com/eetann/choomame

**Comment by eetann** [comment]
Thank you for installing!

Actually, as for Amazing Searcher, it is not supported by https://www.google.co.th and can only be used with https://www.google.com.

Choomame supports https://www.google.co.th, but from your screenshot it doesn't seem to work.

It could be one of the following
* a bug in this extension
  The solutions is one of the following
  * Go to chrome://extensions/ and make sure Choomame is enabled
  * Go to chrome://extensions/ and reload Chooomame
  * Go to the extension's options page (click on the Choomame icon in the list of extensions in the upper right corner, click on Option (the display differs depending on the language)), and press the Reset button
  * Uninstall Choomame and install it again
* Interference with other extensions
  * solution: Turn off other extensions and reload the Google search page

If none of the above works, I will need to investigate. This will take a long time.
